Revert "BACKPORT: arm64: Add support ARCH_SUPPORTS_INT128"
This commit causes linking errors with AOSP's GCC 4.9.4:

kernel/built-in.o: In function `mul_u64_u32_shr':
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151: undefined reference to `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3a790): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151: undefined reference to `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3ae64): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151: undefined reference to `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3b020): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151: undefined reference to `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3b040): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151: undefined reference to `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3b0d4): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__multi3'
kernel/built-in.o:/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151: more undefined references to `__multi3' follow
kernel/built-in.o: In function `mul_u64_u32_shr':
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3b314): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3b338): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3b568): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3b888): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3b8b4): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__multi3'
/home/nathan/kernels/flash/marlin/out/../include/linux/math64.h:151:(.text+0x3ba4c): additional relocation overflows omitted from the output
make[1]: *** [/home/nathan/kernels/flash/marlin/Makefile:963: vmlinux] Error 1

I missed that this was reverted upstream in commit d770b5a04790 ("Revert
"arm64: Add support ARCH_SUPPORTS_INT128""). Additionally, I already
have the replacement for it, commit fb8722735f50 ("arm64: support
__int128 on gcc 5+") as 45a0a70e08ee.

This reverts commit aebd0a0a030fcde95a85728ab1a0482f7b04cfdd.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: khusika <khusikadhamar@gmail.com>